before_install:
  - wget https://archive.apache.org/dist/kafka/0.10.2.1/kafka_2.11-0.10.2.1.tgz
  - tar -xzf kafka_2.11-0.10.2.1.tgz && cd kafka_2.11-0.10.2.1
  - bin/zookeeper-server-start.sh -daemon config/zookeeper.properties
  - bin/kafka-server-start.sh -daemon config/server.properties
  - for i in {1..10}; do bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test && break || sleep 5; done
  - cd $TRAVIS_BUILD_DIR
cache:
  directories:
    - $HOME/.cache/rebar3
install: true
language: erlang
notifications:
  email: false
otp_release:
  - 22.0
  - 21.3
  - 20.3
  - 19.3
script: "make travis"
sudo: false
